export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_STATUS = "AUTH_STATUS";

export const ADD_FARMER = 'ADD_FARMER';
// export const GET_FARMER = 'GET_FARMER';
// export const DELETE_FARMER = 'DELETE_FARMER';

export const LOCATIONS_RECEIVED = 'LOCATIONS_RECEIVED';
export const LOCATION_RESULTS_RECEIVED = 'LOCATION_RESULTS_RECEIVED';
export const LOCATION_DATA_RECEIVED = 'LOCATION_DATA_RECEIVED';
export const RESET_LOCATION = 'RESET_LOCATION';
export const GET_ADMINISTRATION_DATA = 'GET_ADMINISTRATION_DATA';

export const POINT_DATA_RECEIVED = 'POINT_DATA_RECEIVED';

export const ADD_BUYER = 'ADD_BUYER';